# Define input_select
input_select:
  sofar_energy_storage_mode:
    name: Sofar Energy Storage Mode 
    options:
      - "Self use"
      - "Time of use"
      - "Timing mode"
      - "Passive mode"
      - "Peak cut mode"
    icon: mdi:target
  desired_power:
    name: Sofar Desired Power
    options:
      - "-5000"
      - "-4500"
      - "-4000"
      - "-3500"
      - "-3000"
      - "-2500"
      - "-2000"
      - "-1500"
      - "-1000"
      - "-500"
      - "0"
      - "500"
      - "1000"
      - "1500"
      - "2000"
      - "2500"
      - "3000"
      - "3500"
      - "4000"
      - "4500"
      - "5000"
    icon: mdi:target

# Automation.
automation: 
- alias: "Set Sofar Energy Storage Mode Selector"
  trigger:
    platform: mqtt
    topic: "sofar/energy_storage_mode"
    entity_id: input_select.sofar_energy_storage_mode
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.sofar_energy_storage_mode
      data:
        option: "{{ trigger.payload }}"
- alias: "Set Sofar Desired Power Selector"
  trigger:
    platform: mqtt
    topic: "sofar/desired_power"
    entity_id: input_select.desired_power
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.desired_power
      data:
        option: "{{ trigger.payload }}"
- alias: "Set Sofar Energy Storage Mode"
  trigger:
    platform: state
    entity_id: input_select.sofar_energy_storage_mode
  action:
    - service: mqtt.publish
      data:
        topic: "sofar/rw/energy_storage_mode"
        retain: false
        payload: "{{ states('input_select.sofar_energy_storage_mode') }}"
- alias: "Set Sofar Desired power"
  trigger:
    platform: state
    entity_id: input_select.desired_power
  action:
    - service: mqtt.publish
      data:
        topic: "sofar/rw/desired_power"
        retain: false
        payload: "{{ states('input_select.desired_power') }}"
