sensor:
- name: Sofar:Modbus failures
  state_class: measurement
  state_topic: sofar/modbus_failures
  unique_id: sofar_modbus_failures
- name: Sofar:Modbus requests
  state_class: measurement
  state_topic: sofar/modbus_requests
  unique_id: sofar_modbus_requests
- name: Sofar:Modbus failure rate
  state_class: measurement
  state_topic: sofar/modbus_failure_rate
  unique_id: sofar_modbus_failure_rate
  unit_of_measurement: '%'
- icon: mdi:power-standby
  name: Sofar:Inverter state
  state_class: measurement
  state_topic: sofar/state
  unique_id: Sofar_inverter_state
- icon: mdi:home-battery
  name: Sofar:Mode
  state_topic: sofar/energy_storage_mode
  unique_id: Sofar_mode
- icon: mdi:battery-clock-outline
  name: Sofar:Time of use
  state_class: measurement
  state_topic: sofar/time_of_use
  unique_id: Sofar_time_of_use
- icon: mdi:battery-clock-outline
  name: Sofar:Time of use - Start time
  state_class: measurement
  state_topic: sofar/time_of_use_charge_start_time
  unique_id: Sofar_time_of_use_start_time
- icon: mdi:battery-clock-outline
  name: Sofar:Time of use - End time
  state_class: measurement
  state_topic: sofar/time_of_use_charge_end_time
  unique_id: Sofar_time_of_use_end_time
- icon: mdi:battery-clock-outline
  name: Sofar:Time of use - SOC
  state_class: measurement
  state_topic: sofar/time_of_use_charge_soc
  unique_id: Sofar_time_of_use_soc
- icon: mdi:battery-clock-outline
  name: Sofar:Time of use - Power
  state_class: measurement
  state_topic: sofar/time_of_use_charge_power
  unique_id: Sofar_time_of_use_power
- icon: mdi:battery-clock-outline
  name: Sofar:Time of use - Start date
  state_class: measurement
  state_topic: sofar/time_of_use_start_date
  unique_id: Sofar_time_of_use_start_date
- icon: mdi:battery-clock-outline
  name: Sofar:Time of use - End date
  state_class: measurement
  state_topic: sofar/time_of_use_end_date
  unique_id: Sofar_time_of_use_end_date
- icon: mdi:calendar-today-outline
  name: Sofar:Time of use - DoW
  state_class: measurement
  state_topic: sofar/time_of_use_dow
  unique_id: Sofar_time_of_use_dow
- device_class: power
  icon: mdi:solar-power-variant
  name: Sofar:Solar PV1 voltage now
  state_class: measurement
  state_topic: sofar/pv_1_voltage
  unique_id: sofar_pv1_voltage_now
  unit_of_measurement: V
- device_class: current
  icon: mdi:solar-power-variant
  name: Sofar:Solar PV1 current now
  state_class: measurement
  state_topic: sofar/pv_1_current
  unique_id: sofar_pv1_current_now
  unit_of_measurement: A
- device_class: power
  icon: mdi:solar-power-variant
  name: Sofar:Solar PV1 power now
  state_class: measurement
  state_topic: sofar/pv_1_power
  unique_id: sofar_pv1_power_now
  unit_of_measurement: W
- device_class: voltage
  icon: mdi:solar-power-variant
  name: Sofar:Solar PV2 voltage now
  state_class: measurement
  state_topic: sofar/pv_2_voltage
  unique_id: sofar_pv2_voltage_now
  unit_of_measurement: V
- device_class: current
  icon: mdi:solar-power-variant
  name: Sofar:Solar PV2 current now
  state_class: measurement
  state_topic: sofar/pv_2_current
  unique_id: sofar_pv2_current_now
  unit_of_measurement: A
- device_class: power
  icon: mdi:solar-power-variant
  name: Sofar:Solar PV2 power now
  state_class: measurement
  state_topic: sofar/pv_2_power
  unique_id: sofar_pv2_power_now
  unit_of_measurement: W
- device_class: power
  icon: mdi:solar-power-variant
  name: Sofar:Solar power now
  state_class: measurement
  state_topic: sofar/pv_total_power
  unique_id: sofar_solar_power_now
  unit_of_measurement: W
- device_class: power
  icon: mdi:flash
  name: Sofar:Active power
  state_class: measurement
  state_topic: sofar/active_power
  unique_id: sofar_active_power
  unit_of_measurement: W
- device_class: power
  icon: mdi:home-import-outline
  name: Sofar:House consumption now
  state_class: measurement
  state_topic: sofar/load_power
  unique_id: sofar_house_consumption_now
  unit_of_measurement: W
- device_class: power
  icon: mdi:flash
  name: Sofar:Grid power
  state_class: measurement
  state_topic: sofar/grid
  unique_id: sofar_grid_power
  unit_of_measurement: W
- device_class: energy
  icon: mdi:flash
  name: Sofar:Insulation Resistance
  state_class: measurement
  state_topic: sofar/insulation_resistance
  unique_id: sofar_insultation_resistance
  unit_of_measurement: Ohms
- device_class: frequency
  icon: mdi:flash
  name: Sofar:Ongrid Frequency
  state_class: measurement
  state_topic: sofar/ongrid_frequency
  unique_id: sofar_ongrid_frequency
  unit_of_measurement: Hz
- device_class: voltage
  icon: mdi:battery-charging-high
  name: Sofar:Ongrid Voltage
  state_class: measurement
  state_topic: sofar/ongrid_voltage
  unique_id: sofar_ongrid_voltage
  unit_of_measurement: V
- device_class: temperature
  icon: mdi:thermometer
  name: Sofar:Inverter temp (internal)
  state_class: measurement
  state_topic: sofar/inverter_temp_internal
  unique_id: Sofar_inverter_temp_internal
  unit_of_measurement: C
- device_class: temperature
  icon: mdi:thermometer
  name: Sofar:Inverter temp (heatsink)
  state_class: measurement
  state_topic: sofar/inverter_temp_heatsink
  unique_id: Sofar_inverter_temp_heatsink
  unit_of_measurement: C
- device_class: power
  icon: mdi:flash
  name: Sofar:Offgrid Active power
  state_class: measurement
  state_topic: sofar/offgrid_active_power
  unique_id: sofar_offgrid_active_power
  unit_of_measurement: W
- device_class: frequency
  icon: mdi:flash
  name: Sofar:Offgrid Frequency
  state_class: measurement
  state_topic: sofar/offgrid_frequency
  unique_id: sofar_offgrid_frequency
  unit_of_measurement: Hz
- device_class: voltage
  icon: mdi:battery-charging-high
  name: Sofar:Offgrid Voltage
  state_class: measurement
  state_topic: sofar/offgrid_voltage
  unique_id: sofar_offgrid_voltage
  unit_of_measurement: V
- device_class: current
  icon: mdi:battery-charging-50
  name: Sofar:Battery current
  state_class: measurement
  state_topic: sofar/battery_current
  unique_id: sofar_battery_current_now
  unit_of_measurement: A
- device_class: power
  icon: mdi:battery-charging-50
  name: Sofar:Battery power
  state_class: measurement
  state_topic: sofar/battery_power
  unique_id: sofar_battery_power_now
  unit_of_measurement: W
- device_class: energy
  icon: mdi:solar-power
  name: Sofar:Solar generation (today)
  state_class: total_increasing
  state_topic: sofar/today_generation
  unique_id: sofar_solar_generation_today
  unit_of_measurement: kWh
- device_class: energy
  icon: mdi:home-import-outline
  name: Sofar:Consumption (today)
  state_class: total_increasing
  state_topic: sofar/today_consumption
  unique_id: Sofar_consumption_today
  unit_of_measurement: kWh
- device_class: energy
  icon: mdi:home-import-outline
  name: Sofar:Import (today)
  state_class: total_increasing
  state_topic: sofar/today_import
  unique_id: Sofar_import_today
  unit_of_measurement: kWh
- device_class: energy
  icon: mdi:home-export-outline
  name: Sofar:Export (today)
  state_class: total_increasing
  state_topic: sofar/today_export
  unique_id: Sofar_export_today
  unit_of_measurement: kWh
- device_class: energy
  icon: mdi:battery-charging-50
  name: Sofar:Battery discharge (today)
  state_class: total_increasing
  state_topic: sofar/today_battery_discharge
  unique_id: sofar_battery_discharge_today
  unit_of_measurement: kWh
- device_class: energy
  icon: mdi:battery-charging
  name: Sofar:Battery charge (today)
  state_class: total_increasing
  state_topic: sofar/today_battery_charge
  unique_id: sofar_battery_charge_today
  unit_of_measurement: kWh
- device_class: energy
  icon: mdi:battery-charging-high
  name: Sofar Battery:Voltage
  state_class: measurement
  state_topic: sofar/battery_voltage
  unique_id: sofar_battery_voltage
  unit_of_measurement: V
- device_class: temperature
  icon: mdi:thermometer
  name: Sofar Battery:Temp
  state_class: measurement
  state_topic: sofar/battery_temp
  unique_id: sofar_battery_temp
  unit_of_measurement: C
- device_class: battery
  icon: mdi:battery-charging-outline
  name: Sofar:Battery SoC
  state_class: measurement
  state_topic: sofar/battery_soc
  unique_id: Sofar_battery_SoC
  unit_of_measurement: '%'
- device_class: battery
  icon: mdi:battery-charging-outline
  name: Sofar:Battery SoH
  state_class: measurement
  state_topic: sofar/battery_soh
  unique_id: Sofar_battery_SoH
  unit_of_measurement: '%'
- icon: mdi:battery-clock-outline
  name: Sofar:Battery cycles
  state_class: measurement
  state_topic: sofar/battery_cycles
  unique_id: Sofar_battery_cycles
